version: "3.3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: otus
      KEYCLOAK_PASSWORD: otus
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
